modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0-only"

[[mods]]
modId = "iris"

version = "1.7.1"
displayName = "Iris"

logoFile="iris-logo.png" #optional

authors="coderbot, IMS212"

description = '''
Iris is a modern shaders mod for Minecraft intended to be compatible with existing OptiFine shader packs.
'''

[[dependencies.sodium]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "mixins.iris.json"

[[mixins]]
config = "mixins.iris.fantastic.json"

[[mixins]]
config = "mixins.iris.vertexformat.json"

[[mixins]]
config = "iris-batched-entity-rendering.mixins.json"

[[mixins]]
config = "mixins.iris.compat.sodium.json"

[[mixins]]
config = "mixins.iris.forge.json"

[mods."sodium:options"]
"mixin.features.render.world.sky"=false
"mixin.features.render.entity"=false
"mixin.features.render.gui.font"=false
